const symbolGroups = [
['SONICUSDT_PERP.A,SSVUSDT_PERP.A,IOSTUSDT_PERP.A,POWRUSDT_PERP.A,PHAUSDT_PERP.A,PEOPLEUSDT_PERP.A,DYMUSDT_PERP.A,CHRUSDT_PERP.A,YGGUSDT_PERP.A,ONGUSDT_PERP.A,CETUSUSDT_PERP.A,XVGUSDT_PERP.A,DOGSUSDT_PERP.A,ILVUSDT_PERP.A,BANANAUSDT_PERP.A,PARTIUSDT_PERP.A,VVVUSDT_PERP.A,CELRUSDT_PERP.A,TRBUSDT_PERP.A,CGPTUSDT_PERP.A'],
['DENTUSDT_PERP.A,JOEUSDT_PERP.A,KMNOUSDT_PERP.A,AGLDUSDT_PERP.A,DFUSDT_PERP.A,ALCHUSDT_PERP.A,BBUSDT_PERP.A,XAIUSDT_PERP.A,LQTYUSDT_PERP.A,TNSRUSDT_PERP.A,SHELLUSDT_PERP.A,USTCUSDT_PERP.A,KNCUSDT_PERP.A,OXTUSDT_PERP.A,NMRUSDT_PERP.A,SCRUSDT_PERP.A,STEEMUSDT_PERP.A,C98USDT_PERP.A,SCRTUSDT_PERP.A,BANANAS31USDT_PERP.A'],
['VANRYUSDT_PERP.A,MTLUSDT_PERP.A,ARKUSDT_PERP.A,HIFIUSDT_PERP.A,CTSIUSDT_PERP.A,GOATUSDT_PERP.A,PONKEUSDT_PERP.A,EDUUSDT_PERP.A,MOVRUSDT_PERP.A,COOKIEUSDT_PERP.A,BELUSDT_PERP.A,TSTUSDT_PERP.A,CYBERUSDT_PERP.A,BANUSDT_PERP.A,RAREUSDT_PERP.A,LUMIAUSDT_PERP.A,GPSUSDT_PERP.A,DODOXUSDT_PERP.A,AIUSDT_PERP.A,DUSKUSDT_PERP.A'],
['OMNIUSDT_PERP.A,BNTUSDT_PERP.A,ALICEUSDT_PERP.A,ARCUSDT_PERP.A,SOLVUSDT_PERP.A,TRUUSDT_PERP.A,NTRNUSDT_PERP.A,PORTALUSDT_PERP.A,DIAUSDT_PERP.A,DEGENUSDT_PERP.A,HIGHUSDT_PERP.A,OGNUSDT_PERP.A,RIFUSDT_PERP.A,CATIUSDT_PERP.A,STGUSDT_PERP.A,GRIFFAINUSDT_PERP.A,SAGAUSDT_PERP.A,ARPAUSDT_PERP.A,BAKEUSDT_PERP.A,MOODENGUSDT_PERP.A'],
['HIPPOUSDT_PERP.A,HFTUSDT_PERP.A,MAGICUSDT_PERP.A,MAVUSDT_PERP.A,ACEUSDT_PERP.A,SIRENUSDT_PERP.A,SYSUSDT_PERP.A,ATAUSDT_PERP.A,DEGOUSDT_PERP.A,DUSDT_PERP.A,BMTUSDT_PERP.A,NKNUSDT_PERP.A,AVAAIUSDT_PERP.A,SWARMSUSDT_PERP.A,NFPUSDT_PERP.A,THEUSDT_PERP.A,MBOXUSDT_PERP.A,LISTAUSDT_PERP.A,REZUSDT_PERP.A,ZEREBROUSDT_PERP.A'],
['TLMUSDT_PERP.A,SYNUSDT_PERP.A,GTCUSDT_PERP.A,FIDAUSDT_PERP.A,HOOKUSDT_PERP.A,PHBUSDT_PERP.A,SLERFUSDT_PERP.A,SWELLUSDT_PERP.A,HEIUSDT_PERP.A,RDNTUSDT_PERP.A,CHILLGUYUSDT_PERP.A,BRUSDT_PERP.A,1000RATSUSDT_PERP.A,VICUSDT_PERP.A,EPICUSDT_PERP.A,GHSTUSDT_PERP.A,REIUSDT_PERP.A,SANTOSUSDT_PERP.A,VINEUSDT_PERP.A,MAVIAUSDT_PERP.A'],
['PERPUSDT_PERP.A,LOKAUSDT_PERP.A,FLMUSDT_PERP.A,AVAUSDT_PERP.A,KOMAUSDT_PERP.A,QUICKUSDT_PERP.A,COSUSDT_PERP.A,JELLYJELLYUSDT_PERP.A,CHESSUSDT_PERP.A,VOXELUSDT_PERP.A,MYROUSDT_PERP.A,PIPPINUSDT_PERP.A,TOKENUSDT_PERP.A,TUTUSDT_PERP.A,FIOUSDT_PERP.A,BIDUSDT_PERP.A,RAYSOLUSDT_PERP.A,1000CHEEMSUSDT_PERP.A,BROCCOLIF3BUSDT_PERP.A,DEFIUSDT_PERP.A'],
['VELODROMEUSDT_PERP.A,1000XUSDT_PERP.A,1000WHYUSDT_PERP.A,1000CATUSDT_PERP.A,BROCCOLI714USDT_PERP.A,BTCDOMUSDT_PERP.A,FUNUSDT_PERP.A,MLNUSDT_PERP.A,GUNUSDT_PERP.A,ATHUSDT_PERP.A,BANKUSDT_PERP.A,WCTUSDT_PERP.A,SXTUSDT_PERP.A,AIOTUSDT_PERP.A,DOLOUSDT_PERP.A,HAEDALUSDT_PERP.A,PUNDIXUSDT_PERP.A,CTKUSDT_PERP.A,SIGNUSDT_PERP.A,JSTUSDT_PERP.A'],
['MEMEFIUSDT_PERP.A,INITUSDT_PERP.A,HYPERUSDT_PERP.A,BABYUSDT_PERP.A,PROMPTUSDT_PERP.A,XCNUSDT_PERP.A,FORTHUSDT_PERP.A,SAHARAUSDT_PERP.A,OLUSDT_PERP.A,BULLAUSDT_PERP.A,IDOLUSDT_PERP.A,MUSDT_PERP.A,MYXUSDT_PERP.A,FUSDT_PERP.A,NEWTUSDT_PERP.A,TAIKOUSDT_PERP.A,SQDUSDT_PERP.A,MERLUSDT_PERP.A,HYPEUSDT_PERP.A,PUFFERUSDT_PERP.A'],
['PORT3USDT_PERP.A,1000000BOBUSDT_PERP.A,LAUSDT_PERP.A,BUSDT_PERP.A,SOONUSDT_PERP.A,HUMAUSDT_PERP.A,ZKJUSDT_PERP.A,CVCUSDT_PERP.A,AGTUSDT_PERP.A,AWEUSDT_PERP.A,ASRUSDT_PERP.A,ALPINEUSDT_PERP.A,B2USDT_PERP.A,MILKUSDT_PERP.A,SYRUPUSDT_PERP.A,SXTUSDT_PERP.A,SLPUSDT_PERP.A,ZORAUSDT_PERP.A,TAGUSDT_PERP.A,ZRCUSDT_PERP.A'],
['ESPORTSUSDT_PERP.A,PUMPUSDT_PERP.A,CROSSUSDT_PERP.A,AINUSDT_PERP.A,CUSDT_PERP.A,VELVETUSDT_PERP.A,OGUSDT_PERP.A,TREEUSDT_PERP.A,A2ZUSDT_PERP.A,LINEAUSDT_PERP.A,WLFIUSDT_PERP.A,SOMIUSDT_PERP.A,ARIAUSDT_PERP.A,TAKEUSDT_PERP.A,AVNTUSDT_PERP.A,WLFIUSDC_PERP.A,MITOUSDT_PERP.A,BASUSDT_PERP.A,HEMIUSDT_PERP.A,PTBUSDT_PERP.A'],
['QUSDT_PERP.A,SAPIENUSDT_PERP.A,CUDISUSDT_PERP.A,XPLUSDT_PERP.A,BTRUSDT_PERP.A,USELESSUSDT_PERP.A,AIOUSDT_PERP.A,XNYUSDT_PERP.A,CARVUSDT_PERP.A,YALAUSDT_PERP.A,TOWNSUSDT_PERP.A,PROVEUSDT_PERP.A,INUSDT_PERP.A,COAIUSDT_PERP.A,HANAUSDT_PERP.A,FLUIDUSDT_PERP.A,LIGHTUSDT_PERP.A,0GUSDT_PERP.A,BARDUSDT_PERP.A,ASTERUSDT_PERP.A'],
['TRADOORUSDT_PERP.A,BLESSUSDT_PERP.A,XANUSDT_PERP.A,XPINUSDT_PERP.A,ZKCUSDT_PERP.A,AIAUSDT_PERP.A,TOSHIUSDT_PERP.A,STBLUSDT_PERP.A,OPENUSDT_PERP.A,FLOCKUSDT_PERP.A,SKYUSDT_PERP.A,UBUSDT_PERP.A,HOLOUSDT_PERP.A'],

];





module.exports = symbolGroups;

